version: "3.9"

services:
  # Backend API (.NET)
  apiservice:
    build:
      context: .
      dockerfile: src/TodojsAspire.ApiService/Dockerfile
    container_name: todo_api
    ports:
      - "8081:5000" # Local: truy cập http://localhost:8081
    environment:
      - ConnectionStrings__db=Host=postgres_db;Database=tododb;Username=user;Password=password
    depends_on:
      postgres_db:
        condition: service_healthy

  # Frontend (React + Vite build, served by Nginx)
  frontend:
    build:
      context: src/todo-frontend
      dockerfile: Dockerfile
    container_name: todo_frontend
    ports:
      - "8080:80" # Local: http://localhost:8080
    environment:
      - VITE_API_URL=/api # frontend gọi /api, Nginx proxy sang backend
    depends_on:
      - apiservice

  # PostgreSQL database
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Local connect DB qua localhost:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
