version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: example
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: sbackend:latest
    depends_on:
      - db
    environment:
      ConnectionStrings__Database: "server=db;port=3306;database=example;user id=root;password=secret"
    ports:
      - "5001:80"

  sfrontend:
    build:
      context: ./view
      dockerfile: Dockerfile
    image: sfrontend
    environment:
      APP_API_HOST: "backend"
      APP_API_PORT: "80"
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db-data:
